from tkinter import *
from tkinter import messagebox
top = Tk()
top.title("219414 calculator")
L1=Label(top,text="value 1: ")
L1.pack(side=LEFT)
L1.place(x=15,y=40)
E1=Entry(top,bd=8)
E1.pack(side=RIGHT)
E1.place(x=80,y=40)
L2=Label(top,text="value 2 : ")
L2.pack(side=RIGHT)
L2.place(x=15,y=120)
E2=Entry(top,bd=8)
E2.pack(side=RIGHT)
E2.place(x=80,y=120)
top.geometry("300x300")
def add() :
    c=int(E1.get())+int(E2.get())
    s="addition is : ",str(c)
    msg=messagebox.showinfo('Calculator',s)
B=Button(top,text=" + ",command=add)
B.place(x=50,y=200)
def sub():
    c=int(E1.get())-int(E2.get())
    s="Subtraction is : ",str(c)
    msg=messagebox.showinfo('Calculator',s)
B=Button(top,text=" - ",command=sub)
B.place(x=110,y=200)
def mul():
    c=int(E1.get())*int(E2.get())
    s="Multiplication is : ",str(x)
    msg=messagebox.showinfo('Calculator',s)
B=Button(top,text=" * ",command=mul)
B.place(x=170,y=200)
def div():
    c=int(E1.get())//int(E2.get())
    s="Division is ",str(c)
    msg=messagebox.showinfo('Calculator',s)
B=Button(top,text=" / ",command=div)
B.place(x=230,y=200)
top.mainloop()
