f1=open("abc.txt","w")
n=input("enter the text :")
f1.write(n)
f2=open("xyz.txt","w")
n=input("enter the text :")
f2.write(n)
f1.close()
f2.close()
f3=open("lmn.txt","w")
f1=open("abc.txt","r")
f3.write(f1.read())
f2=open("xyz.txt","r")
f3.write(f2.read())
f1.close()
f2.close()
f3.close()
